+incdir+${ROOT}/hardware/ip/axi/include

${ROOT}/hardware/ip/axi/src/axi_pkg.sv
${ROOT}/hardware/ip/axi/src/axi_intf.sv
${ROOT}/hardware/ip/axi/src/axi_atop_filter.sv
${ROOT}/hardware/ip/axi/src/axi_burst_splitter.sv
${ROOT}/hardware/ip/axi/src/axi_bus_compare.sv
${ROOT}/hardware/ip/axi/src/axi_cdc_dst.sv
${ROOT}/hardware/ip/axi/src/axi_cdc_src.sv
${ROOT}/hardware/ip/axi/src/axi_cut.sv
${ROOT}/hardware/ip/axi/src/axi_delayer.sv
${ROOT}/hardware/ip/axi/src/axi_demux_simple.sv
${ROOT}/hardware/ip/axi/src/axi_dw_downsizer.sv
${ROOT}/hardware/ip/axi/src/axi_dw_upsizer.sv
${ROOT}/hardware/ip/axi/src/axi_fifo.sv
${ROOT}/hardware/ip/axi/src/axi_id_remap.sv
${ROOT}/hardware/ip/axi/src/axi_id_prepend.sv
${ROOT}/hardware/ip/axi/src/axi_isolate.sv
${ROOT}/hardware/ip/axi/src/axi_join.sv
${ROOT}/hardware/ip/axi/src/axi_lite_demux.sv
${ROOT}/hardware/ip/axi/src/axi_lite_dw_converter.sv
${ROOT}/hardware/ip/axi/src/axi_lite_from_mem.sv
${ROOT}/hardware/ip/axi/src/axi_lite_join.sv
${ROOT}/hardware/ip/axi/src/axi_lite_lfsr.sv
${ROOT}/hardware/ip/axi/src/axi_lite_mailbox.sv
${ROOT}/hardware/ip/axi/src/axi_lite_mux.sv
${ROOT}/hardware/ip/axi/src/axi_lite_regs.sv
${ROOT}/hardware/ip/axi/src/axi_lite_to_apb.sv
${ROOT}/hardware/ip/axi/src/axi_lite_to_axi.sv
${ROOT}/hardware/ip/axi/src/axi_modify_address.sv
${ROOT}/hardware/ip/axi/src/axi_mux.sv
${ROOT}/hardware/ip/axi/src/axi_rw_join.sv
${ROOT}/hardware/ip/axi/src/axi_rw_split.sv
${ROOT}/hardware/ip/axi/src/axi_serializer.sv
${ROOT}/hardware/ip/axi/src/axi_slave_compare.sv
${ROOT}/hardware/ip/axi/src/axi_throttle.sv
${ROOT}/hardware/ip/axi/src/axi_to_detailed_mem.sv
${ROOT}/hardware/ip/axi/src/axi_cdc.sv
${ROOT}/hardware/ip/axi/src/axi_demux.sv
${ROOT}/hardware/ip/axi/src/axi_err_slv.sv
${ROOT}/hardware/ip/axi/src/axi_dw_converter.sv
${ROOT}/hardware/ip/axi/src/axi_from_mem.sv
${ROOT}/hardware/ip/axi/src/axi_id_serialize.sv
${ROOT}/hardware/ip/axi/src/axi_lfsr.sv
${ROOT}/hardware/ip/axi/src/axi_multicut.sv
${ROOT}/hardware/ip/axi/src/axi_to_axi_lite.sv
${ROOT}/hardware/ip/axi/src/axi_to_mem.sv
${ROOT}/hardware/ip/axi/src/axi_zero_mem.sv
${ROOT}/hardware/ip/axi/src/axi_interleaved_xbar.sv
${ROOT}/hardware/ip/axi/src/axi_iw_converter.sv
${ROOT}/hardware/ip/axi/src/axi_lite_xbar.sv
${ROOT}/hardware/ip/axi/src/axi_xbar_unmuxed.sv
${ROOT}/hardware/ip/axi/src/axi_to_mem_banked.sv
${ROOT}/hardware/ip/axi/src/axi_to_mem_interleaved.sv
${ROOT}/hardware/ip/axi/src/axi_to_mem_split.sv
${ROOT}/hardware/ip/axi/src/axi_xbar.sv
${ROOT}/hardware/ip/axi/src/axi_xp.sv

${ROOT}/hardware/ip/axi/src/axi_inval_filter.sv
${ROOT}/hardware/ip/axi/src/axi_lite_interface.sv
${ROOT}/hardware/ip/axi/src/axi2mem.sv
