#!/usr/bin/env python3
"""Convert a .f filelist (with -f includes, ${ROOT}, +incdir+, +define+)
into a Vivado TCL script with read_verilog, include_dirs, and verilog_define.

Usage:
    python3 gen_vivado_filelist.py <filelist.f> <root_dir> [-o output.tcl]
"""

import argparse
import os
import re
import sys


def resolve_vars(line, variables):
    """Replace ${VAR} with values from variables dict."""
    def replacer(m):
        return variables.get(m.group(1), m.group(0))
    return re.sub(r'\$\{(\w+)\}', replacer, line)


def parse_filelist(flist_path, variables, files, incdirs, defines, seen=None):
    """Recursively parse a .f filelist."""
    if seen is None:
        seen = set()

    flist_path = os.path.normpath(flist_path)
    if flist_path in seen:
        return
    seen.add(flist_path)

    base_dir = os.path.dirname(flist_path)

    with open(flist_path, 'r') as f:
        for raw_line in f:
            line = re.sub(r'//.*$', '', raw_line).strip()
            if not line:
                continue

            line = resolve_vars(line, variables)

            # -f recursive include
            if line.startswith('-f '):
                sub_path = line[3:].strip()
                if not os.path.isabs(sub_path):
                    sub_path = os.path.join(base_dir, sub_path)
                parse_filelist(sub_path, variables, files, incdirs, defines, seen)
                continue

            # +incdir+
            if line.startswith('+incdir+'):
                path = line[8:].strip()
                if not os.path.isabs(path):
                    path = os.path.join(base_dir, path)
                incdirs.add(os.path.normpath(path))
                continue

            # +define+
            if line.startswith('+define+'):
                defines.add(line[8:].strip())
                continue

            # -I (alternative incdir)
            if line.startswith('-I'):
                path = line[2:].strip()
                if not os.path.isabs(path):
                    path = os.path.join(base_dir, path)
                incdirs.add(os.path.normpath(path))
                continue

            # Source file
            if not os.path.isabs(line):
                line = os.path.join(base_dir, line)
            files.append(os.path.normpath(line))


def main():
    parser = argparse.ArgumentParser(description='Convert .f filelist to Vivado TCL')
    parser.add_argument('filelist', help='Input .f filelist')
    parser.add_argument('root', help='Value for ${ROOT} variable')
    parser.add_argument('-o', '--output', default='sources.tcl', help='Output TCL file')
    args = parser.parse_args()

    root = os.path.normpath(os.path.abspath(args.root))
    variables = {'ROOT': root}

    files = []
    incdirs = set()
    defines = set()
    parse_filelist(args.filelist, variables, files, incdirs, defines)

    # Deduplicate files while preserving order
    seen = set()
    unique_files = []
    for f in files:
        if f not in seen:
            seen.add(f)
            unique_files.append(f)

    with open(args.output, 'w') as out:
        out.write('# Auto-generated by gen_vivado_filelist.py\n')
        out.write(f'# Source: {args.filelist}\n\n')

        # Source files
        for f in unique_files:
            if f.endswith('.v'):
                out.write(f'read_verilog {{{f}}}\n')
            else:
                out.write(f'read_verilog -sv {{{f}}}\n')

        # Include dirs
        if incdirs:
            out.write('\n# Include directories\n')
            out.write('set_property include_dirs [list \\\n')
            for d in sorted(incdirs):
                out.write(f'  {{{d}}} \\\n')
            out.write('] [get_filesets sources_1]\n')

        # Defines
        if defines:
            out.write('\n# Verilog defines from filelists\n')
            defs_str = ' '.join(sorted(defines))
            out.write(f'set_property verilog_define {{{defs_str}}} [get_filesets sources_1]\n')

        out.write(f'\n# Total: {len(unique_files)} files, {len(incdirs)} include dirs\n')

    print(f'Generated {args.output} with {len(unique_files)} files, {len(incdirs)} include dirs.')


if __name__ == '__main__':
    main()
