module axu_top #(
    parameter int unsigned NUM_LANE        = 64,
    parameter int unsigned ELEM_WIDTH      = 16,
    parameter int unsigned ES              = 2,
    parameter int unsigned BANK_WIDTH      = 128,
    parameter int unsigned BANK_NUM        = (NUM_LANE * ELEM_WIDTH) / BANK_WIDTH,
    parameter int unsigned ADDR_WIDTH      = 8,
    parameter int unsigned CFG_ADDR_WIDTH  = 4,
    parameter int unsigned ALIGN_WIDTH     = 14,
    parameter int unsigned ACC_ALIGN_WIDTH = 32,
    parameter int unsigned SFU_LANE        = NUM_LANE / 2,
    parameter int unsigned SFU_RAND_N      = ELEM_WIDTH,
    parameter int unsigned SFU_ALIGN_WIDTH = ACC_ALIGN_WIDTH,
    parameter int unsigned SFU_NUM_ITER    = 7,
    parameter int unsigned NLI_NUM_LANES   = SFU_LANE,
    parameter int unsigned NLI_NUM_MACROS  = 10,
    parameter int unsigned NLI_NUM_MICROS  = 32,
    parameter int          BUF_AXI_ADDR_WIDTH = 64,
    parameter int          BUF_AXI_DATA_WIDTH = 64
) (
    input  logic                      clk_i,
    input  logic                      rstn_i,

    input  logic                      cfg_set_i,
    input  logic [CFG_ADDR_WIDTH-1:0] cfg_addr_i,
    input  logic [ADDR_WIDTH-1:0]     cfg_data_i,
    input  logic                      start_i,
    input  logic                      dump_i,

    output logic                      calc_done_o,
    output logic                      busy_o,
    output logic                      done_o,

    input  logic                                 op_a_acc_rd_port_sel_i,
    input  logic                                 op_a_acc_wr_port_sel_i,
    input  logic                                 op_a_axi_req_i,
    input  logic                                 op_a_axi_write_en_i,
    input  logic [BUF_AXI_ADDR_WIDTH-1:0]        op_a_axi_addr_i,
    input  logic [BUF_AXI_DATA_WIDTH/8-1:0]      op_a_axi_byte_en_i,
    input  logic [BUF_AXI_DATA_WIDTH-1:0]        op_a_axi_wdata_i,
    output logic [BUF_AXI_DATA_WIDTH-1:0]        op_a_axi_rdata_o,

    input  logic                                 op_b_acc_rd_port_sel_i,
    input  logic                                 op_b_acc_wr_port_sel_i,
    input  logic                                 op_b_axi_req_i,
    input  logic                                 op_b_axi_write_en_i,
    input  logic [BUF_AXI_ADDR_WIDTH-1:0]        op_b_axi_addr_i,
    input  logic [BUF_AXI_DATA_WIDTH/8-1:0]      op_b_axi_byte_en_i,
    input  logic [BUF_AXI_DATA_WIDTH-1:0]        op_b_axi_wdata_i,
    output logic [BUF_AXI_DATA_WIDTH-1:0]        op_b_axi_rdata_o,

    input  logic                                 out_acc_rd_port_sel_i,
    input  logic                                 out_acc_wr_port_sel_i,
    input  logic                                 out_axi_req_i,
    input  logic                                 out_axi_write_en_i,
    input  logic [BUF_AXI_ADDR_WIDTH-1:0]        out_axi_addr_i,
    input  logic [BUF_AXI_DATA_WIDTH/8-1:0]      out_axi_byte_en_i,
    input  logic [BUF_AXI_DATA_WIDTH-1:0]        out_axi_wdata_i,
    output logic [BUF_AXI_DATA_WIDTH-1:0]        out_axi_rdata_o
);

    axu_top_gate u_axu_top_gate (
        .clk_i                  (clk_i),
        .rstn_i                 (rstn_i),
        .cfg_set_i              (cfg_set_i),
        .cfg_addr_i             (cfg_addr_i),
        .cfg_data_i             (cfg_data_i),
        .start_i                (start_i),
        .dump_i                 (dump_i),
        .calc_done_o            (calc_done_o),
        .busy_o                 (busy_o),
        .done_o                 (done_o),
        .op_a_acc_rd_port_sel_i (op_a_acc_rd_port_sel_i),
        .op_a_acc_wr_port_sel_i (op_a_acc_wr_port_sel_i),
        .op_a_axi_req_i         (op_a_axi_req_i),
        .op_a_axi_write_en_i    (op_a_axi_write_en_i),
        .op_a_axi_addr_i        (op_a_axi_addr_i),
        .op_a_axi_byte_en_i     (op_a_axi_byte_en_i),
        .op_a_axi_wdata_i       (op_a_axi_wdata_i),
        .op_a_axi_rdata_o       (op_a_axi_rdata_o),
        .op_b_acc_rd_port_sel_i (op_b_acc_rd_port_sel_i),
        .op_b_acc_wr_port_sel_i (op_b_acc_wr_port_sel_i),
        .op_b_axi_req_i         (op_b_axi_req_i),
        .op_b_axi_write_en_i    (op_b_axi_write_en_i),
        .op_b_axi_addr_i        (op_b_axi_addr_i),
        .op_b_axi_byte_en_i     (op_b_axi_byte_en_i),
        .op_b_axi_wdata_i       (op_b_axi_wdata_i),
        .op_b_axi_rdata_o       (op_b_axi_rdata_o),
        .out_acc_rd_port_sel_i  (out_acc_rd_port_sel_i),
        .out_acc_wr_port_sel_i  (out_acc_wr_port_sel_i),
        .out_axi_req_i          (out_axi_req_i),
        .out_axi_write_en_i     (out_axi_write_en_i),
        .out_axi_addr_i         (out_axi_addr_i),
        .out_axi_byte_en_i      (out_axi_byte_en_i),
        .out_axi_wdata_i        (out_axi_wdata_i),
        .out_axi_rdata_o        (out_axi_rdata_o)
    );

endmodule
