/*
###############################################################
#  Generated by:      Cadence Innovus 23.10-p003_1
#  OS:                Linux x86_64(Host ID EDA01.R760)
#  Generated on:      Sun Jun  7 13:52:24 2026
#  Design:            DCO
#  Command:           saveNetlist -excludeCellInst {TAPCELLBWP7T40P140 FILL2BWP7T40P140HVT FILL3BWP7T40P140HVT DCAP4BWP7T40P140HVT DCAP8BWP7T40P140HVT DCAP16BWP7T40P140HVT DCAP32BWP7T40P140HVT DCAP64BWP7T40P140HVT BOUNDARY_LEFTBWP7T40P140 BOUNDARY_RIGHTBWP7T40P140 PCORNER PFILLER20 PFILLER10 PFILLER5 PFILLER1 PFILLER05 PFILLER0005} -excludeLeafCell -topModuleFirst ../DCO/DCO_hier_postpnr.v
###############################################################
*/
module DCO (
	EN, 
	CC_SEL, 
	FC_SEL, 
	EXT_CLK, 
	CLK_SEL, 
	DIV_SEL, 
	FREQ_SEL, 
	CLK, 
	CLK_DIV, 
	RSTN);
   input EN;
   input [5:0] CC_SEL;
   input [5:0] FC_SEL;
   input EXT_CLK;
   input CLK_SEL;
   input [1:0] DIV_SEL;
   input [1:0] FREQ_SEL;
   output CLK;
   output CLK_DIV;
   input RSTN;

   // Internal wires
   wire EN_I;
   wire RSTN_I;
   wire EXT_CLK_I;
   wire CLK_SEL_I;
   wire RING_OUT;
   wire CLK_SELECT;
   wire DIV_CLK_OUT;
   wire CLK_I;
   wire [5:0] CC_SEL_I;
   wire [5:0] FC_SEL_I;
   wire [1:0] DIV_SEL_I;
   wire [1:0] FREQ_SEL_I;

   BUF_61 bufen (.Y(EN_I),
	.A(EN));
   BUF_60 bufrstn (.Y(RSTN_I),
	.A(RSTN));
   BUF_59 bufdcosel_0 (.Y(CC_SEL_I[0]),
	.A(CC_SEL[0]));
   BUF_58 bufdcosel_1 (.Y(CC_SEL_I[1]),
	.A(CC_SEL[1]));
   BUF_57 bufdcosel_2 (.Y(CC_SEL_I[2]),
	.A(CC_SEL[2]));
   BUF_56 bufdcosel_3 (.Y(CC_SEL_I[3]),
	.A(CC_SEL[3]));
   BUF_55 bufdcosel_4 (.Y(CC_SEL_I[4]),
	.A(CC_SEL[4]));
   BUF_54 bufdcosel_5 (.Y(CC_SEL_I[5]),
	.A(CC_SEL[5]));
   BUF_53 bufdfine_0 (.Y(FC_SEL_I[0]),
	.A(FC_SEL[0]));
   BUF_52 bufdfine_1 (.Y(FC_SEL_I[1]),
	.A(FC_SEL[1]));
   BUF_51 bufdfine_2 (.Y(FC_SEL_I[2]),
	.A(FC_SEL[2]));
   BUF_50 bufdfine_3 (.Y(FC_SEL_I[3]),
	.A(FC_SEL[3]));
   BUF_49 bufdfine_4 (.Y(FC_SEL_I[4]),
	.A(FC_SEL[4]));
   BUF_48 bufdfine_5 (.Y(FC_SEL_I[5]),
	.A(FC_SEL[5]));
   BUF_47 bufdivsel_0 (.Y(DIV_SEL_I[0]),
	.A(DIV_SEL[0]));
   BUF_46 bufdivsel_1 (.Y(DIV_SEL_I[1]),
	.A(DIV_SEL[1]));
   BUF_45 bufextclk (.Y(EXT_CLK_I),
	.A(EXT_CLK));
   BUF_44 bufclksel (.Y(CLK_SEL_I),
	.A(CLK_SEL));
   BUF_43 buffreqsel_0 (.Y(FREQ_SEL_I[0]),
	.A(FREQ_SEL[0]));
   BUF_42 buffreqsel_1 (.Y(FREQ_SEL_I[1]),
	.A(FREQ_SEL[1]));
   DCO_RING DCO_CORE (.EN(EN_I),
	.DCLK(RING_OUT),
	.SEL(CC_SEL_I),
	.FC_SEL(FC_SEL_I));
   MUX_6 mux_clk (.Y(CLK_SELECT),
	.SEL(CLK_SEL_I),
	.A(RING_OUT),
	.B(EXT_CLK_I));
   MX_CLK_DIVIDER_1 DIVIDER_TEST (.CLK_IN(CLK_SELECT),
	.CLK_OUT(DIV_CLK_OUT),
	.SEL(DIV_SEL_I),
	.FRSTN(RSTN_I));
   MX_CLK_DIVIDER_0 DIVIDER_CLK (.CLK_IN(CLK_SELECT),
	.CLK_OUT(CLK_I),
	.SEL(FREQ_SEL_I),
	.FRSTN(RSTN_I));
   CLK_BUF_CHAIN_1 bufdclk (.Y(CLK),
	.A(CLK_I));
   CLK_BUF_CHAIN_0 bufdivclk (.Y(CLK_DIV),
	.A(DIV_CLK_OUT));
endmodule

/////////////////////////////////////////////////////////////
// Created by: Synopsys Design Compiler(R)
// Version   : V-2023.12-SP3
// Date      : Thu Jun  4 20:46:55 2026
/////////////////////////////////////////////////////////////
module BUF_61 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module VARIABLE_CAP_20 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module BUF_31 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_31 (
	Y, 
	A);
   output Y;
   input A;

   BUF_31 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_34 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_35 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_36 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_37 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_38 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_39 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_40 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_41 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module MUX_0 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module MUX_1 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module MUX_2 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module MUX_3 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module MUX_4 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module MUX_5 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module VARIABLE_CAP_0 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_1 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_2 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_3 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_4 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_5 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_6 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_7 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_8 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_9 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_10 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_11 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_12 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_13 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_14 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_15 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_16 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_17 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_18 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module VARIABLE_CAP_19 (
	EN, 
	A);
   input EN;
   input A;

   ND2D4BWP7T40P140HVT nand2_cell (.A1(A),
	.A2(EN));
endmodule

module BUF_0 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_0 (
	Y, 
	A);
   output Y;
   input A;

   BUF_0 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_1 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_1 (
	Y, 
	A);
   output Y;
   input A;

   BUF_1 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_2 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_2 (
	Y, 
	A);
   output Y;
   input A;

   BUF_2 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_3 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_3 (
	Y, 
	A);
   output Y;
   input A;

   BUF_3 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_4 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_4 (
	Y, 
	A);
   output Y;
   input A;

   BUF_4 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_5 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_5 (
	Y, 
	A);
   output Y;
   input A;

   BUF_5 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_6 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_6 (
	Y, 
	A);
   output Y;
   input A;

   BUF_6 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_7 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_7 (
	Y, 
	A);
   output Y;
   input A;

   BUF_7 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_8 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_8 (
	Y, 
	A);
   output Y;
   input A;

   BUF_8 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_9 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_9 (
	Y, 
	A);
   output Y;
   input A;

   BUF_9 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_10 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_10 (
	Y, 
	A);
   output Y;
   input A;

   BUF_10 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_11 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_11 (
	Y, 
	A);
   output Y;
   input A;

   BUF_11 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_12 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_12 (
	Y, 
	A);
   output Y;
   input A;

   BUF_12 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_13 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_13 (
	Y, 
	A);
   output Y;
   input A;

   BUF_13 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_14 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_14 (
	Y, 
	A);
   output Y;
   input A;

   BUF_14 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_15 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_15 (
	Y, 
	A);
   output Y;
   input A;

   BUF_15 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_16 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_16 (
	Y, 
	A);
   output Y;
   input A;

   BUF_16 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_17 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_17 (
	Y, 
	A);
   output Y;
   input A;

   BUF_17 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_18 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_18 (
	Y, 
	A);
   output Y;
   input A;

   BUF_18 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_19 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_19 (
	Y, 
	A);
   output Y;
   input A;

   BUF_19 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_20 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_20 (
	Y, 
	A);
   output Y;
   input A;

   BUF_20 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_21 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_21 (
	Y, 
	A);
   output Y;
   input A;

   BUF_21 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_22 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_22 (
	Y, 
	A);
   output Y;
   input A;

   BUF_22 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_23 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_23 (
	Y, 
	A);
   output Y;
   input A;

   BUF_23 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_24 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_24 (
	Y, 
	A);
   output Y;
   input A;

   BUF_24 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_25 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_25 (
	Y, 
	A);
   output Y;
   input A;

   BUF_25 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_26 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_26 (
	Y, 
	A);
   output Y;
   input A;

   BUF_26 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_27 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_27 (
	Y, 
	A);
   output Y;
   input A;

   BUF_27 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_28 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_28 (
	Y, 
	A);
   output Y;
   input A;

   BUF_28 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_29 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_29 (
	Y, 
	A);
   output Y;
   input A;

   BUF_29 buf1 (.Y(Y),
	.A(A));
endmodule

module BUF_30 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module DELAY_STEP_30 (
	Y, 
	A);
   output Y;
   input A;

   BUF_30 buf1 (.Y(Y),
	.A(A));
endmodule

module DCO_RING (
	EN, 
	DCLK, 
	SEL, 
	FC_SEL);
   input EN;
   output DCLK;
   input [5:0] SEL;
   input [5:0] FC_SEL;

   // Internal wires
   wire [6:0] A;
   wire [6:0] A_tmp;
   wire [5:0] B;
   wire [1:1] int2;
   wire [3:1] int3;
   wire [7:1] int4;
   wire [15:1] int5;

   VARIABLE_CAP_20 XVARIABLE_CAP0_1 (.EN(FC_SEL[0]),
	.A(A[0]));
   VARIABLE_CAP_19 XVARIABLE_CAP1_1 (.EN(FC_SEL[1]),
	.A(A[0]));
   VARIABLE_CAP_18 XVARIABLE_CAP1_2 (.EN(FC_SEL[1]),
	.A(A[0]));
   VARIABLE_CAP_17 XVARIABLE_CAP2_1 (.EN(FC_SEL[2]),
	.A(A[1]));
   VARIABLE_CAP_16 XVARIABLE_CAP2_2 (.EN(FC_SEL[2]),
	.A(A[1]));
   VARIABLE_CAP_15 XVARIABLE_CAP2_3 (.EN(FC_SEL[2]),
	.A(A[1]));
   VARIABLE_CAP_14 XVARIABLE_CAP3_1 (.EN(FC_SEL[3]),
	.A(A[2]));
   VARIABLE_CAP_13 XVARIABLE_CAP3_2 (.EN(FC_SEL[3]),
	.A(A[2]));
   VARIABLE_CAP_12 XVARIABLE_CAP3_3 (.EN(FC_SEL[3]),
	.A(A[2]));
   VARIABLE_CAP_11 XVARIABLE_CAP3_4 (.EN(FC_SEL[3]),
	.A(A[2]));
   VARIABLE_CAP_10 XVARIABLE_CAP4_1 (.EN(FC_SEL[4]),
	.A(A[3]));
   VARIABLE_CAP_9 XVARIABLE_CAP4_2 (.EN(FC_SEL[4]),
	.A(A[3]));
   VARIABLE_CAP_8 XVARIABLE_CAP4_3 (.EN(FC_SEL[4]),
	.A(A[3]));
   VARIABLE_CAP_7 XVARIABLE_CAP4_4 (.EN(FC_SEL[4]),
	.A(A[3]));
   VARIABLE_CAP_6 XVARIABLE_CAP4_5 (.EN(FC_SEL[4]),
	.A(A[4]));
   VARIABLE_CAP_5 XVARIABLE_CAP5_1 (.EN(FC_SEL[5]),
	.A(A[4]));
   VARIABLE_CAP_4 XVARIABLE_CAP5_2 (.EN(FC_SEL[5]),
	.A(A[4]));
   VARIABLE_CAP_3 XVARIABLE_CAP5_3 (.EN(FC_SEL[5]),
	.A(A[4]));
   VARIABLE_CAP_2 XVARIABLE_CAP5_4 (.EN(FC_SEL[5]),
	.A(A[5]));
   VARIABLE_CAP_1 XVARIABLE_CAP5_5 (.EN(FC_SEL[5]),
	.A(A[5]));
   VARIABLE_CAP_0 XVARIABLE_CAP5_6 (.EN(FC_SEL[5]),
	.A(A[5]));
   ND2D2BWP7T40P140HVT nanden (.A1(A[6]),
	.A2(EN),
	.ZN(A_tmp[0]));
   BUF_41 buf_a0 (.Y(A[0]),
	.A(A_tmp[0]));
   BUF_40 buffers (.Y(DCLK),
	.A(A[6]));
   MUX_5 mux0 (.Y(A_tmp[1]),
	.SEL(SEL[0]),
	.A(A[0]),
	.B(B[0]));
   BUF_39 buf_a1 (.Y(A[1]),
	.A(A_tmp[1]));
   DELAY_STEP_31 buf0_0 (.Y(B[0]),
	.A(A[0]));
   MUX_4 mux1 (.Y(A_tmp[2]),
	.SEL(SEL[1]),
	.A(A[1]),
	.B(B[1]));
   BUF_38 buf_a2 (.Y(A[2]),
	.A(A_tmp[2]));
   DELAY_STEP_30 buf1_0 (.Y(B[1]),
	.A(A[1]));
   MUX_3 mux2 (.Y(A_tmp[3]),
	.SEL(SEL[2]),
	.A(A[2]),
	.B(B[2]));
   BUF_37 buf_a3 (.Y(A[3]),
	.A(A_tmp[3]));
   DELAY_STEP_29 buf2_0 (.Y(int2[1]),
	.A(A[2]));
   DELAY_STEP_28 buf2_1 (.Y(B[2]),
	.A(int2[1]));
   MUX_2 mux3 (.Y(A_tmp[4]),
	.SEL(SEL[3]),
	.A(A[3]),
	.B(B[3]));
   BUF_36 buf_a4 (.Y(A[4]),
	.A(A_tmp[4]));
   DELAY_STEP_27 buf3_0 (.Y(int3[1]),
	.A(A[3]));
   DELAY_STEP_26 buf3_1 (.Y(int3[2]),
	.A(int3[1]));
   DELAY_STEP_25 buf3_2 (.Y(int3[3]),
	.A(int3[2]));
   DELAY_STEP_24 buf3_3 (.Y(B[3]),
	.A(int3[3]));
   MUX_1 mux4 (.Y(A_tmp[5]),
	.SEL(SEL[4]),
	.A(A[4]),
	.B(B[4]));
   BUF_35 buf_a5 (.Y(A[5]),
	.A(A_tmp[5]));
   DELAY_STEP_23 buf4_0 (.Y(int4[1]),
	.A(A[4]));
   DELAY_STEP_22 buf4_1 (.Y(int4[2]),
	.A(int4[1]));
   DELAY_STEP_21 buf4_2 (.Y(int4[3]),
	.A(int4[2]));
   DELAY_STEP_20 buf4_3 (.Y(int4[4]),
	.A(int4[3]));
   DELAY_STEP_19 buf4_4 (.Y(int4[5]),
	.A(int4[4]));
   DELAY_STEP_18 buf4_5 (.Y(int4[6]),
	.A(int4[5]));
   DELAY_STEP_17 buf4_6 (.Y(int4[7]),
	.A(int4[6]));
   DELAY_STEP_16 buf4_7 (.Y(B[4]),
	.A(int4[7]));
   MUX_0 mux5 (.Y(A_tmp[6]),
	.SEL(SEL[5]),
	.A(A[5]),
	.B(B[5]));
   BUF_34 buf_a6 (.Y(A[6]),
	.A(A_tmp[6]));
   DELAY_STEP_15 buf5_0 (.Y(int5[1]),
	.A(A[5]));
   DELAY_STEP_14 buf5_1 (.Y(int5[2]),
	.A(int5[1]));
   DELAY_STEP_13 buf5_2 (.Y(int5[3]),
	.A(int5[2]));
   DELAY_STEP_12 buf5_3 (.Y(int5[4]),
	.A(int5[3]));
   DELAY_STEP_11 buf5_4 (.Y(int5[5]),
	.A(int5[4]));
   DELAY_STEP_10 buf5_5 (.Y(int5[6]),
	.A(int5[5]));
   DELAY_STEP_9 buf5_6 (.Y(int5[7]),
	.A(int5[6]));
   DELAY_STEP_8 buf5_7 (.Y(int5[8]),
	.A(int5[7]));
   DELAY_STEP_7 buf5_8 (.Y(int5[9]),
	.A(int5[8]));
   DELAY_STEP_6 buf5_9 (.Y(int5[10]),
	.A(int5[9]));
   DELAY_STEP_5 buf5_10 (.Y(int5[11]),
	.A(int5[10]));
   DELAY_STEP_4 buf5_11 (.Y(int5[12]),
	.A(int5[11]));
   DELAY_STEP_3 buf5_12 (.Y(int5[13]),
	.A(int5[12]));
   DELAY_STEP_2 buf5_13 (.Y(int5[14]),
	.A(int5[13]));
   DELAY_STEP_1 buf5_14 (.Y(int5[15]),
	.A(int5[14]));
   DELAY_STEP_0 buf5_15 (.Y(B[5]),
	.A(int5[15]));
endmodule

module MUX_6 (
	Y, 
	SEL, 
	A, 
	B);
   output Y;
   input SEL;
   input A;
   input B;

   MUX2D4BWP7T40P140HVT mux2 (.I0(A),
	.I1(B),
	.S(SEL),
	.Z(Y));
endmodule

module BUF_33 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module MX_CLK_DIVIDER_1 (
	CLK_IN, 
	CLK_OUT, 
	SEL, 
	FRSTN);
   input CLK_IN;
   output CLK_OUT;
   input [1:0] SEL;
   input FRSTN;

   // Internal wires
   wire FE_OFN1_n_5;
   wire clk_div_sel;
   wire n_3;
   wire div4_q;
   wire div2_q;
   wire n_2;
   wire n_1;
   wire n_5;
   wire n_0;
   wire n_4;

   BUFFD0BWP7T40P140HVT FE_OFC1_n_5 (.I(n_5),
	.Z(FE_OFN1_n_5));
   BUF_33 bufmx (.Y(CLK_OUT),
	.A(clk_div_sel));
   DFCNQD1BWP7T40P140HVT div4_q_reg (.CDN(FRSTN),
	.CP(CLK_IN),
	.D(n_3),
	.Q(div4_q));
   XOR2D2BWP7T40P140HVT g32 (.A1(div2_q),
	.A2(div4_q),
	.Z(n_3));
   DFCNQD1BWP7T40P140HVT div2_q_reg (.CDN(FRSTN),
	.CP(CLK_IN),
	.D(n_2),
	.Q(div2_q));
   INVD0BWP7T40P140HVT g34 (.I(div2_q),
	.ZN(n_2));
   OAI221D0BWP7T40P140HVT g55 (.A1(div4_q),
	.A2(n_1),
	.B1(SEL[1]),
	.B2(div2_q),
	.C(SEL[0]),
	.ZN(n_5));
   INVD0BWP7T40P140HVT g56 (.I(SEL[1]),
	.ZN(n_1));
   CKND2D8BWP7T40P140HVT g49 (.A1(n_0),
	.A2(FE_OFN1_n_5),
	.ZN(clk_div_sel));
   ND2D16BWP7T40P140HVT g50 (.A1(CLK_IN),
	.A2(n_4),
	.ZN(n_0));
   CKND1BWP7T40P140HVT g51 (.I(SEL[0]),
	.ZN(n_4));
endmodule

module CLK_BUF_CHAIN_1 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire [3:0] int1;

   BUFFD1BWP7T40P140HVT buf1 (.I(A),
	.Z(int1[0]));
   BUFFD4BWP7T40P140HVT buf2 (.I(int1[0]),
	.Z(int1[1]));
   BUFFD8BWP7T40P140HVT buf3 (.I(int1[1]),
	.Z(int1[2]));
   BUFFD12BWP7T40P140HVT buf4 (.I(int1[2]),
	.Z(int1[3]));
   BUFFD20BWP7T40P140HVT buf5 (.I(int1[3]),
	.Z(Y));
endmodule

module BUF_42 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_43 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_44 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_45 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module BUF_46 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_47 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_48 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_49 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_50 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_51 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_52 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_53 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_54 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_55 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_56 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_57 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_58 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_59 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_60 (
	Y, 
	A);
   output Y;
   input A;

   assign Y = A ;
endmodule

module BUF_32 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire tmp;

   INVD1BWP7T40P140HVT buf1 (.I(A),
	.ZN(tmp));
   INVD2BWP7T40P140HVT buf2 (.I(tmp),
	.ZN(Y));
endmodule

module MX_CLK_DIVIDER_0 (
	CLK_IN, 
	CLK_OUT, 
	SEL, 
	FRSTN);
   input CLK_IN;
   output CLK_OUT;
   input [1:0] SEL;
   input FRSTN;

   // Internal wires
   wire FE_OFN0_n_5;
   wire clk_div_sel;
   wire n_3;
   wire div4_q;
   wire div2_q;
   wire n_2;
   wire n_1;
   wire n_5;
   wire n_0;
   wire n_4;

   BUFFD0BWP7T40P140HVT FE_OFC0_n_5 (.I(n_5),
	.Z(FE_OFN0_n_5));
   BUF_32 bufmx (.Y(CLK_OUT),
	.A(clk_div_sel));
   DFCNQD1BWP7T40P140HVT div4_q_reg (.CDN(FRSTN),
	.CP(CLK_IN),
	.D(n_3),
	.Q(div4_q));
   XOR2D2BWP7T40P140HVT g32 (.A1(div2_q),
	.A2(div4_q),
	.Z(n_3));
   DFCNQD1BWP7T40P140HVT div2_q_reg (.CDN(FRSTN),
	.CP(CLK_IN),
	.D(n_2),
	.Q(div2_q));
   INVD0BWP7T40P140HVT g34 (.I(div2_q),
	.ZN(n_2));
   OAI221D0BWP7T40P140HVT g55 (.A1(div4_q),
	.A2(n_1),
	.B1(SEL[1]),
	.B2(div2_q),
	.C(SEL[0]),
	.ZN(n_5));
   INVD0BWP7T40P140HVT g56 (.I(SEL[1]),
	.ZN(n_1));
   CKND2D8BWP7T40P140HVT g49 (.A1(n_0),
	.A2(FE_OFN0_n_5),
	.ZN(clk_div_sel));
   ND2D16BWP7T40P140HVT g50 (.A1(CLK_IN),
	.A2(n_4),
	.ZN(n_0));
   CKND1BWP7T40P140HVT g51 (.I(SEL[0]),
	.ZN(n_4));
endmodule

module CLK_BUF_CHAIN_0 (
	Y, 
	A);
   output Y;
   input A;

   // Internal wires
   wire [3:0] int1;

   BUFFD1BWP7T40P140HVT buf1 (.I(A),
	.Z(int1[0]));
   BUFFD4BWP7T40P140HVT buf2 (.I(int1[0]),
	.Z(int1[1]));
   BUFFD8BWP7T40P140HVT buf3 (.I(int1[1]),
	.Z(int1[2]));
   BUFFD12BWP7T40P140HVT buf4 (.I(int1[2]),
	.Z(int1[3]));
   BUFFD20BWP7T40P140HVT buf5 (.I(int1[3]),
	.Z(Y));
endmodule

