${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_atomics_structs.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_lrsc_wrap.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_amos.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_amos_wrap.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_lrsc.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_riscv_atomics.sv
${ROOT}/hardware/ip/axi_riscv_atomics/src/axi_res_tbl.sv