+incdir+../hardware/ip/ara/include

../hardware/ip/ara/include/rvv_pkg.sv
../hardware/ip/ara/include/ara_pkg.sv
../hardware/ip/ara/src/segment_sequencer.sv
../hardware/ip/ara/src/ara_dispatcher.sv
../hardware/ip/ara/src/ara_sequencer.sv
../hardware/ip/ara/src/lane/lane_sequencer.sv
../hardware/ip/ara/src/lane/operand_queue.sv
../hardware/ip/ara/src/lane/operand_requester.sv
../hardware/ip/ara/src/lane/simd_alu.sv
../hardware/ip/ara/src/lane/simd_div.sv
../hardware/ip/ara/src/lane/simd_mul.sv
../hardware/ip/ara/src/lane/vector_regfile.sv
../hardware/ip/ara/src/lane/power_gating_generic.sv
../hardware/ip/ara/src/masku/masku_operands.sv
../hardware/ip/ara/src/sldu/p2_stride_gen.sv
../hardware/ip/ara/src/sldu/sldu_op_dp.sv
../hardware/ip/ara/src/sldu/sldu.sv
../hardware/ip/ara/src/vlsu/addrgen.sv
../hardware/ip/ara/src/vlsu/vldu.sv
../hardware/ip/ara/src/vlsu/vstu.sv
../hardware/ip/ara/src/lane/operand_queues_stage.sv
../hardware/ip/ara/src/lane/valu.sv
../hardware/ip/ara/src/lane/vmfpu.sv
../hardware/ip/ara/src/lane/fixed_p_rounding.sv
../hardware/ip/ara/src/vlsu/vlsu.sv
../hardware/ip/ara/src/masku/masku.sv
../hardware/ip/ara/src/lane/vector_fus_stage.sv
../hardware/ip/ara/src/lane/lane.sv
../hardware/ip/ara/src/ara.sv
