+incdir+${ROOT}/hardware/ip/ara/include

${ROOT}/hardware/ip/ara/include/rvv_pkg.sv
${ROOT}/hardware/ip/ara/include/ara_pkg.sv
${ROOT}/hardware/ip/ara/src/segment_sequencer.sv
${ROOT}/hardware/ip/ara/src/ara_dispatcher.sv
${ROOT}/hardware/ip/ara/src/ara_sequencer.sv
${ROOT}/hardware/ip/ara/src/lane/lane_sequencer.sv
${ROOT}/hardware/ip/ara/src/lane/operand_queue.sv
${ROOT}/hardware/ip/ara/src/lane/operand_requester.sv
${ROOT}/hardware/ip/ara/src/lane/simd_alu.sv
${ROOT}/hardware/ip/ara/src/lane/simd_div.sv
${ROOT}/hardware/ip/ara/src/lane/simd_mul.sv
${ROOT}/hardware/ip/ara/src/lane/vector_regfile.sv
${ROOT}/hardware/ip/ara/src/lane/power_gating_generic.sv
${ROOT}/hardware/ip/ara/src/masku/masku_operands.sv
${ROOT}/hardware/ip/ara/src/sldu/p2_stride_gen.sv
${ROOT}/hardware/ip/ara/src/sldu/sldu_op_dp.sv
${ROOT}/hardware/ip/ara/src/sldu/sldu.sv
${ROOT}/hardware/ip/ara/src/vlsu/addrgen.sv
${ROOT}/hardware/ip/ara/src/vlsu/vldu.sv
${ROOT}/hardware/ip/ara/src/vlsu/vstu.sv
${ROOT}/hardware/ip/ara/src/lane/operand_queues_stage.sv
${ROOT}/hardware/ip/ara/src/lane/valu.sv
${ROOT}/hardware/ip/ara/src/lane/vmfpu.sv
${ROOT}/hardware/ip/ara/src/lane/fixed_p_rounding.sv
${ROOT}/hardware/ip/ara/src/vlsu/vlsu.sv
${ROOT}/hardware/ip/ara/src/masku/masku.sv
${ROOT}/hardware/ip/ara/src/lane/vector_fus_stage.sv
${ROOT}/hardware/ip/ara/src/lane/lane.sv
${ROOT}/hardware/ip/ara/src/ara.sv
