+incdir+${ROOT}/hardware/ip/common_cells/include
+define+COMMON_CELLS_ASSERTS_OFF

${ROOT}/hardware/ip/common_cells/src/edge_propagator_ack.sv
${ROOT}/hardware/ip/common_cells/src/binary_to_gray.sv
${ROOT}/hardware/ip/common_cells/src/popcount.sv
${ROOT}/hardware/ip/common_cells/src/isochronous_spill_register.sv
${ROOT}/hardware/ip/common_cells/src/spill_register_flushable.sv
${ROOT}/hardware/ip/common_cells/src/stream_delay.sv
${ROOT}/hardware/ip/common_cells/src/cf_math_pkg.sv
${ROOT}/hardware/ip/common_cells/src/lfsr.sv
${ROOT}/hardware/ip/common_cells/src/stream_arbiter_flushable.sv
${ROOT}/hardware/ip/common_cells/src/rstgen_bypass.sv
${ROOT}/hardware/ip/common_cells/src/edge_propagator_rx.sv
${ROOT}/hardware/ip/common_cells/src/addr_decode_dync.sv
${ROOT}/hardware/ip/common_cells/src/cdc_fifo_2phase.sv
${ROOT}/hardware/ip/common_cells/src/stream_throttle.sv
${ROOT}/hardware/ip/common_cells/src/clk_mux_glitch_free.sv
${ROOT}/hardware/ip/common_cells/src/stream_register.sv
${ROOT}/hardware/ip/common_cells/src/mem_to_banks_detailed.sv
${ROOT}/hardware/ip/common_cells/src/exp_backoff.sv
${ROOT}/hardware/ip/common_cells/src/stream_join_dynamic.sv
${ROOT}/hardware/ip/common_cells/src/mem_to_banks.sv
${ROOT}/hardware/ip/common_cells/src/shift_reg_gated.sv
${ROOT}/hardware/ip/common_cells/src/passthrough_stream_fifo.sv
${ROOT}/hardware/ip/common_cells/src/stream_mux.sv
${ROOT}/hardware/ip/common_cells/src/delta_counter.sv
${ROOT}/hardware/ip/common_cells/src/rstgen.sv
${ROOT}/hardware/ip/common_cells/src/lossy_valid_to_stream.sv
${ROOT}/hardware/ip/common_cells/src/stream_filter.sv
${ROOT}/hardware/ip/common_cells/src/stream_fifo.sv
${ROOT}/hardware/ip/common_cells/src/ecc_pkg.sv
${ROOT}/hardware/ip/common_cells/src/serial_deglitch.sv
${ROOT}/hardware/ip/common_cells/src/isochronous_4phase_handshake.sv
${ROOT}/hardware/ip/common_cells/src/counter.sv
${ROOT}/hardware/ip/common_cells/src/stream_omega_net.sv
${ROOT}/hardware/ip/common_cells/src/lzc.sv
${ROOT}/hardware/ip/common_cells/src/lfsr_8bit.sv
${ROOT}/hardware/ip/common_cells/src/sync.sv
${ROOT}/hardware/ip/common_cells/src/cdc_fifo_gray.sv
${ROOT}/hardware/ip/common_cells/src/stream_to_mem.sv
${ROOT}/hardware/ip/common_cells/src/mv_filter.sv
${ROOT}/hardware/ip/common_cells/src/stream_arbiter.sv
${ROOT}/hardware/ip/common_cells/src/credit_counter.sv
${ROOT}/hardware/ip/common_cells/src/fifo_v3.sv
${ROOT}/hardware/ip/common_cells/src/fifo_v2.sv
${ROOT}/hardware/ip/common_cells/src/fifo_v1.sv
${ROOT}/hardware/ip/common_cells/src/edge_propagator_tx.sv
${ROOT}/hardware/ip/common_cells/src/boxcar.sv
${ROOT}/hardware/ip/common_cells/src/heaviside.sv
${ROOT}/hardware/ip/common_cells/src/sub_per_hash.sv
${ROOT}/hardware/ip/common_cells/src/cdc_reset_ctrlr_pkg.sv
${ROOT}/hardware/ip/common_cells/src/cdc_4phase.sv
${ROOT}/hardware/ip/common_cells/src/ecc_encode.sv
${ROOT}/hardware/ip/common_cells/src/cb_filter_pkg.sv
${ROOT}/hardware/ip/common_cells/src/cb_filter.sv
${ROOT}/hardware/ip/common_cells/src/cdc_fifo_gray_clearable.sv
${ROOT}/hardware/ip/common_cells/src/fall_through_register.sv
${ROOT}/hardware/ip/common_cells/src/trip_counter.sv
${ROOT}/hardware/ip/common_cells/src/clk_int_div.sv
${ROOT}/hardware/ip/common_cells/src/addr_decode_napot.sv
${ROOT}/hardware/ip/common_cells/src/cdc_2phase_clearable.sv
${ROOT}/hardware/ip/common_cells/src/unread.sv
${ROOT}/hardware/ip/common_cells/src/stream_intf.sv
${ROOT}/hardware/ip/common_cells/src/max_counter.sv
${ROOT}/hardware/ip/common_cells/src/stream_fifo_optimal_wrap.sv
${ROOT}/hardware/ip/common_cells/src/stream_fork_dynamic.sv
${ROOT}/hardware/ip/common_cells/src/cdc_reset_ctrlr.sv
${ROOT}/hardware/ip/common_cells/src/stream_demux.sv
${ROOT}/hardware/ip/common_cells/src/onehot_to_bin.sv
${ROOT}/hardware/ip/common_cells/src/rr_arb_tree.sv
${ROOT}/hardware/ip/common_cells/src/multiaddr_decode.sv
${ROOT}/hardware/ip/common_cells/src/ring_buffer.sv
${ROOT}/hardware/ip/common_cells/src/spill_register.sv
${ROOT}/hardware/ip/common_cells/src/stream_xbar.sv
${ROOT}/hardware/ip/common_cells/src/lfsr_16bit.sv
${ROOT}/hardware/ip/common_cells/src/stream_join.sv
${ROOT}/hardware/ip/common_cells/src/shift_reg.sv
${ROOT}/hardware/ip/common_cells/src/cdc_2phase.sv
${ROOT}/hardware/ip/common_cells/src/stream_fork.sv
${ROOT}/hardware/ip/common_cells/src/id_queue.sv
${ROOT}/hardware/ip/common_cells/src/gray_to_binary.sv
${ROOT}/hardware/ip/common_cells/src/sync_wedge.sv
${ROOT}/hardware/ip/common_cells/src/addr_decode.sv
${ROOT}/hardware/ip/common_cells/src/edge_detect.sv
${ROOT}/hardware/ip/common_cells/src/ecc_decode.sv
${ROOT}/hardware/ip/common_cells/src/edge_propagator.sv
${ROOT}/hardware/ip/common_cells/src/plru_tree.sv
${ROOT}/hardware/ip/common_cells/src/clk_int_div_static.sv
${ROOT}/hardware/ip/common_cells/src/read.sv
${ROOT}/hardware/ip/common_cells/src/cc_onehot.sv