${ROOT}/hardware/ip/rv_clic/src/clic_pkg.sv
${ROOT}/hardware/ip/rv_clic/src/clicint_reg_pkg.sv
${ROOT}/hardware/ip/rv_clic/src/clicint_reg_top.sv
${ROOT}/hardware/ip/rv_clic/src/clicintv_reg_pkg.sv
${ROOT}/hardware/ip/rv_clic/src/clicintv_reg_top.sv
${ROOT}/hardware/ip/rv_clic/src/clicvs_reg_pkg.sv
${ROOT}/hardware/ip/rv_clic/src/clicvs_reg_top.sv
${ROOT}/hardware/ip/rv_clic/src/mclic_reg_pkg.sv
${ROOT}/hardware/ip/rv_clic/src/mclic_reg_top.sv
${ROOT}/hardware/ip/rv_clic/src/clic_reg_adapter.sv
${ROOT}/hardware/ip/rv_clic/src/clic_gateway.sv
${ROOT}/hardware/ip/rv_clic/src/clic_target.sv
${ROOT}/hardware/ip/rv_clic/src/clic.sv