${ROOT}/hardware/ip/rv_plic/src/plic_regmap.sv
${ROOT}/hardware/ip/rv_plic/src/rv_plic_target.sv
${ROOT}/hardware/ip/rv_plic/src/rv_plic_gateway.sv
${ROOT}/hardware/ip/rv_plic/src/top_pkg.sv
${ROOT}/hardware/ip/rv_plic/src/rv_plic_reg_pkg.sv
${ROOT}/hardware/ip/rv_plic/src/prim_subreg.sv
${ROOT}/hardware/ip/rv_plic/src/tlul_pkg.sv
${ROOT}/hardware/ip/rv_plic/src/rv_plic.sv
${ROOT}/hardware/ip/rv_plic/src/rv_plic_reg_top.sv
${ROOT}/hardware/ip/rv_plic/src/plic_top.sv
${ROOT}/hardware/ip/rv_plic/src/prim_subreg_ext.sv