../hardware/ip/rv_plic/src/plic_regmap.sv
../hardware/ip/rv_plic/src/rv_plic_target.sv
../hardware/ip/rv_plic/src/rv_plic_gateway.sv
../hardware/ip/rv_plic/src/top_pkg.sv
../hardware/ip/rv_plic/src/rv_plic_reg_pkg.sv
../hardware/ip/rv_plic/src/prim_subreg.sv
../hardware/ip/rv_plic/src/tlul_pkg.sv
../hardware/ip/rv_plic/src/rv_plic.sv
../hardware/ip/rv_plic/src/rv_plic_reg_top.sv
../hardware/ip/rv_plic/src/plic_top.sv
../hardware/ip/rv_plic/src/prim_subreg_ext.sv