+incdir+../hardware/ip/cva6/core/include
+incdir+../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/include
+incdir+../hardware/ip/cva6/common/local/util

../hardware/ip/cva6/core/include/config_pkg.sv
../hardware/ip/cva6/core/include/cv64a6_imafdcv_sv39_config_pkg.sv
../hardware/ip/cva6/core/include/riscv_pkg.sv
../hardware/ip/cva6/core/include/ariane_pkg.sv
../hardware/ip/cva6/core/include/build_config_pkg.sv
../hardware/ip/cva6/core/cva6_mmu/cva6_tlb.sv
../hardware/ip/cva6/core/cva6_mmu/cva6_shared_tlb.sv
../hardware/ip/cva6/core/cva6_mmu/cva6_mmu.sv
../hardware/ip/cva6/core/cva6_mmu/cva6_ptw.sv
../hardware/ip/cva6/core/include/wt_cache_pkg.sv
../hardware/ip/cva6/core/include/std_cache_pkg.sv
../hardware/ip/cva6/core/cvxif_example/include/cvxif_instr_pkg.sv
../hardware/ip/cva6/core/cvxif_fu.sv
../hardware/ip/cva6/core/cvxif_issue_register_commit_if_driver.sv
../hardware/ip/cva6/core/cvxif_compressed_if_driver.sv
../hardware/ip/cva6/core/cvxif_example/cvxif_example_coprocessor.sv
../hardware/ip/cva6/core/cvxif_example/instr_decoder.sv
../hardware/ip/cva6/core/cva6_rvfi.sv
../hardware/ip/cva6/core/cva6_rvfi_probes.sv
../hardware/ip/cva6/core/cva6_fifo_v3.sv
../hardware/ip/cva6/core/cva6.sv
../hardware/ip/cva6/core/alu.sv
../hardware/ip/cva6/core/fpu_wrap.sv
../hardware/ip/cva6/core/branch_unit.sv
../hardware/ip/cva6/core/compressed_decoder.sv
../hardware/ip/cva6/core/controller.sv
../hardware/ip/cva6/core/csr_buffer.sv
../hardware/ip/cva6/core/csr_regfile.sv
../hardware/ip/cva6/core/decoder.sv
../hardware/ip/cva6/core/ex_stage.sv
../hardware/ip/cva6/core/acc_dispatcher.sv
../hardware/ip/cva6/core/instr_realign.sv
../hardware/ip/cva6/core/macro_decoder.sv
../hardware/ip/cva6/core/id_stage.sv
../hardware/ip/cva6/core/issue_read_operands.sv
../hardware/ip/cva6/core/issue_stage.sv
../hardware/ip/cva6/core/load_unit.sv
../hardware/ip/cva6/core/load_store_unit.sv
../hardware/ip/cva6/core/lsu_bypass.sv
../hardware/ip/cva6/core/mult.sv
../hardware/ip/cva6/core/multiplier.sv
../hardware/ip/cva6/core/serdiv.sv
../hardware/ip/cva6/core/perf_counters.sv
../hardware/ip/cva6/core/ariane_regfile_ff.sv
../hardware/ip/cva6/core/ariane_regfile_fpga.sv
../hardware/ip/cva6/core/scoreboard.sv
../hardware/ip/cva6/core/store_buffer.sv
../hardware/ip/cva6/core/amo_buffer.sv
../hardware/ip/cva6/core/store_unit.sv
../hardware/ip/cva6/core/commit_stage.sv
../hardware/ip/cva6/core/axi_shim.sv
../hardware/ip/cva6/core/frontend/btb.sv
../hardware/ip/cva6/core/frontend/bht.sv
../hardware/ip/cva6/core/frontend/ras.sv
../hardware/ip/cva6/core/frontend/instr_scan.sv
../hardware/ip/cva6/core/frontend/instr_queue.sv
../hardware/ip/cva6/core/frontend/frontend.sv
../hardware/ip/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
../hardware/ip/cva6/core/cache_subsystem/wt_dcache_mem.sv
../hardware/ip/cva6/core/cache_subsystem/wt_dcache_missunit.sv
../hardware/ip/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
../hardware/ip/cva6/core/cache_subsystem/wt_dcache.sv
../hardware/ip/cva6/core/cache_subsystem/wt_cache_subsystem.sv
../hardware/ip/cva6/core/cache_subsystem/wt_axi_adapter.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_icache.sv
../hardware/ip/cva6/core/cache_subsystem/tag_cmp.sv
../hardware/ip/cva6/core/cache_subsystem/cache_ctrl.sv
../hardware/ip/cva6/core/cache_subsystem/amo_alu.sv
../hardware/ip/cva6/core/cache_subsystem/axi_adapter.sv
../hardware/ip/cva6/core/cache_subsystem/miss_handler.sv
../hardware/ip/cva6/core/cache_subsystem/std_nbdcache.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
../hardware/ip/cva6/core/cache_subsystem/std_cache_subsystem.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg_initialized.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
../hardware/ip/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
../hardware/ip/cva6/core/cache_subsystem/cva6_hpdcache_wrapper.sv
../hardware/ip/cva6/core/pmp/src/pmp.sv
../hardware/ip/cva6/core/pmp/src/pmp_entry.sv
../hardware/ip/cva6/core/pmp/src/pmp_data_if.sv
../hardware/ip/cva6/core/include/instr_tracer_pkg.sv
../hardware/ip/cva6/common/local/util/instr_tracer.sv
