#!/usr/bin/env python3
import argparse
import csv
from typing import List


# Keep these constants aligned with software/soc/include/dcim.h
DCIM_BASE = 0xE0000000
DCIM_ACT_BASE = DCIM_BASE + 0x40000
DCIM_OUT_BASE = DCIM_BASE + 0x60000
DCIM_WEI_BASE = DCIM_BASE + 0x80000

DCIM_ACT_BANK_SIZE = 0x800
DCIM_OUT_BANK_SIZE = 0x2000
DCIM_WEI_BANK_SIZE = 0x8000

ACT_DEPTH = 64
OUT_DEPTH = 64
WEI_DEPTH = 128


def _u32_to_bin(v: int) -> str:
    return f"{v & 0xFFFFFFFF:032b}"


def _format_row_u32_bin(row_u32: List[int]) -> str:
    return " ".join(_u32_to_bin(x) for x in reversed(row_u32))


def _emit_act_mem(path: str, act_rows_u32: List[List[int]]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for r in range(ACT_DEPTH):
            f.write(_format_row_u32_bin(act_rows_u32[r]) + "\n")


def _emit_res_mem(path: str, out_rows_u32: List[List[int]]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        for r in range(OUT_DEPTH):
            f.write(_format_row_u32_bin(out_rows_u32[r]) + "\n")


def _save_cache_like_wei(path: str, wei_rows_u32: List[List[int]], wei_addr_row: int = 0) -> None:
    """
    Reproduce sim.cpp/save_cache behavior:
      IDX = (ch_out * 64 + ch_in) * 4
      idx1 = IDX / 2048
      idx2 = (IDX % 2048) / 32
      nibble = (weis[idx1 + wei_addr][idx2] >> ((IDX % 32) / 4 * 4)) & 0xF
    """
    with open(path, "w", encoding="utf-8") as f:
        for ch_in in range(63, -1, -1):
            vals = []
            for ch_out in range(63, -1, -1):
                idx = (ch_out * 64 + ch_in) * 4
                idx1 = idx // 2048
                idx2 = (idx % 2048) // 32
                nib_shift = ((idx % 32) // 4) * 4
                word = wei_rows_u32[idx1 + wei_addr_row][idx2]
                vals.append(f"{(word >> nib_shift) & 0xF:01x}")
            f.write(" ".join(vals) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert CPU-side DCIM IO trace to mem files.")
    parser.add_argument(
        "--csv",
        default="dcim_io_trace.csv",
        help="Input csv generated by extract_io.py (default: dcim_io_trace.csv)",
    )
    parser.add_argument("--wei-out", default="wei.mem", help="Output wei.mem path")
    parser.add_argument("--act-out", default="act.mem", help="Output act.mem path")
    parser.add_argument("--res-out", default="res.mem", help="Output res.mem path")
    parser.add_argument(
        "--wei-bank",
        type=int,
        default=0,
        choices=[0, 1, 2, 3],
        help="Which WEI bank to export (default: 0)",
    )
    parser.add_argument(
        "--act-bank",
        type=int,
        default=0,
        choices=[0, 1, 2, 3],
        help="Which ACT bank to export (default: 0)",
    )
    parser.add_argument(
        "--out-bank",
        type=int,
        default=0,
        choices=[0, 1, 2, 3],
        help="Which OUT bank to export (default: 0)",
    )
    args = parser.parse_args()

    # row payloads in u32 lanes:
    # ACT row: 256b  => 8 x u32
    # OUT row: 1024b => 32 x u32
    # WEI row: 2048b => 64 x u32
    act_rows = [[0 for _ in range(8)] for _ in range(ACT_DEPTH)]
    out_rows = [[0 for _ in range(32)] for _ in range(OUT_DEPTH)]
    wei_rows = [[0 for _ in range(64)] for _ in range(WEI_DEPTH)]

    n_w_act = n_w_wei = n_r_out = 0

    with open(args.csv, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            op = row["op"].strip()
            addr = int(row["addr_hex"], 16)
            data = int(row["data_hex"], 16)

            # ACT writes from CPU
            if op == "W_ACT" and DCIM_ACT_BASE <= addr < DCIM_OUT_BASE:
                rel = addr - DCIM_ACT_BASE
                bank = rel // DCIM_ACT_BANK_SIZE
                if bank != args.act_bank:
                    continue
                word64 = (rel % DCIM_ACT_BANK_SIZE) // 8
                row_idx = word64 // 4
                lane64 = word64 % 4
                if 0 <= row_idx < ACT_DEPTH:
                    act_rows[row_idx][lane64 * 2 + 0] = data & 0xFFFFFFFF
                    act_rows[row_idx][lane64 * 2 + 1] = (data >> 32) & 0xFFFFFFFF
                    n_w_act += 1

            # WEI writes from CPU
            elif op == "W_WEI" and DCIM_WEI_BASE <= addr < (DCIM_WEI_BASE + 4 * DCIM_WEI_BANK_SIZE):
                rel = addr - DCIM_WEI_BASE
                bank = rel // DCIM_WEI_BANK_SIZE
                if bank != args.wei_bank:
                    continue
                word64 = (rel % DCIM_WEI_BANK_SIZE) // 8
                row_idx = word64 // 32
                lane64 = word64 % 32
                if 0 <= row_idx < WEI_DEPTH:
                    wei_rows[row_idx][lane64 * 2 + 0] = data & 0xFFFFFFFF
                    wei_rows[row_idx][lane64 * 2 + 1] = (data >> 32) & 0xFFFFFFFF
                    n_w_wei += 1

            # OUT reads by CPU
            elif op == "R_OUT" and DCIM_OUT_BASE <= addr < DCIM_WEI_BASE:
                rel = addr - DCIM_OUT_BASE
                bank = rel // DCIM_OUT_BANK_SIZE
                if bank != args.out_bank:
                    continue
                word64 = (rel % DCIM_OUT_BANK_SIZE) // 8
                row_idx = word64 // 16
                lane64 = word64 % 16
                if 0 <= row_idx < OUT_DEPTH:
                    out_rows[row_idx][lane64 * 2 + 0] = data & 0xFFFFFFFF
                    out_rows[row_idx][lane64 * 2 + 1] = (data >> 32) & 0xFFFFFFFF
                    n_r_out += 1

    _save_cache_like_wei(args.wei_out, wei_rows, wei_addr_row=0)
    _emit_act_mem(args.act_out, act_rows)
    _emit_res_mem(args.res_out, out_rows)

    print(
        f"Generated mem files: {args.wei_out}, {args.act_out}, {args.res_out}\n"
        f"W_ACT captured={n_w_act}, W_WEI captured={n_w_wei}, R_OUT captured={n_r_out}"
    )


if __name__ == "__main__":
    main()

