// FPGA top-level wrapper for ariane_soc_top on AXU15EG
// - Differential clock → MMCM → sys_clk
// - RTC generated by divider from sys_clk
// - JTAG trst tied to rst_ni (no extra button on AXU15EG)

module ariane_soc_top_wrapper #(
  parameter CLK_LED_COUNT_LENGTH = 27,
  parameter RTC_DIV              = 1024  // sys_clk / (2*RTC_DIV) ≈ RTC frequency
) (
  input  logic clk_200mhz_n,
  input  logic clk_200mhz_p,
  input  logic rst_ni,

  // Debug LEDs (PL_LED1: rst/exit, PL_LED2: clk blink)
  output logic rst_exit_led_o,
  output logic clk_led_o,

  // JTAG
  input  logic jtag_tck_i,
  input  logic jtag_tms_i,
  input  logic jtag_tdi_i,
  output logic jtag_tdo_o,

  // UART
  input  logic uart_rx_i,
  output logic uart_tx_o
);

  // ---------------
  // Clock generation
  // ---------------
  wire sys_clk;

  xilinx_clk_wizard_wrapper xilinx_clk_wizard_wrapper_i (
    .CLK_IN1_D_0_clk_n ( clk_200mhz_n ),
    .CLK_IN1_D_0_clk_p ( clk_200mhz_p ),
    .clk_out1_0        ( sys_clk       ),
    .reset_0           ( ~rst_ni       )  // MMCM active-high reset
  );

  // ---------------
  // RTC divider
  // ---------------
  logic [$clog2(RTC_DIV)-1:0] rtc_cnt;
  logic                       rtc_q;

  always_ff @(posedge sys_clk or negedge rst_ni) begin
    if (!rst_ni) begin
      rtc_cnt <= '0;
      rtc_q   <= 1'b0;
    end else if (rtc_cnt == RTC_DIV - 1) begin
      rtc_cnt <= '0;
      rtc_q   <= ~rtc_q;
    end else begin
      rtc_cnt <= rtc_cnt + 1;
    end
  end

  // ---------------
  // Debug LEDs
  // ---------------
  logic [CLK_LED_COUNT_LENGTH-1:0] clk_count;

  // rst_exit_led_o: ON when not in reset and not exited
  assign rst_exit_led_o = rst_ni & ~exit[0];
  assign clk_led_o = clk_count[CLK_LED_COUNT_LENGTH-1];

  always_ff @(posedge sys_clk or negedge rst_ni) begin
    if (!rst_ni)
      clk_count <= '0;
    else
      clk_count <= clk_count + 1;
  end

  // ---------------
  // SoC instance
  // ---------------
  logic [31:0] exit;
  logic jtag_trst_ni;
  assign jtag_trst_ni = rst_ni; // just use system rst

  ariane_soc_top i_ariane_soc_top (
    .clk_i            ( sys_clk       ),
    .rtc_i            ( rtc_q         ),
    .rst_ni           ( rst_ni        ),
    .uart_rx_i        ( uart_rx_i     ),
    .uart_tx_o        ( uart_tx_o     ),
    .exit_o           ( exit          ),
    .jtag_tck_i       ( jtag_tck_i    ),
    .jtag_tms_i       ( jtag_tms_i    ),
    .jtag_tdi_i       ( jtag_tdi_i    ),
    .jtag_trst_ni     ( jtag_trst_ni  ),
    .jtag_tdo_o       ( jtag_tdo_o    ),
    .jtag_tdo_driven_o(               ), // reserved
    .debug_enable_i   ( 1'b1          )
  );

endmodule
