###############################################################################
# syn/scripts/synth.tcl
# Top-level DC NXT synthesis driver.
###############################################################################

# ===========================================================================
# Intercept Makefile variables → internal Tcl variables
# ===========================================================================

proc capture_var {name args} {
    upvar 1 $name var
    if {[info exists var]} { return }                          ;# already set by -x
    if {[info exists ::env($name)]} {
        set var $::env($name)
        return
    }
    if {[llength $args] == 0} {
        error "$name is required but was not passed by the Makefile or environment."
    }
    set var [lindex $args 0]
}

capture_var PDK_ROOT                                           ;# required
capture_var SYN_ROOT                                           ;# required
capture_var BUILD_DIR                                          ;# required
capture_var INCR_MODE         0
capture_var INCR_CHECKPOINT   post_constraints

set env(PDK_ROOT) $PDK_ROOT   ;# keep env in sync for child scripts

# Derived directory layout
set SETUP_DIR   "${SYN_ROOT}/setup"
set SCRIPTS_DIR "${SYN_ROOT}/scripts"
set REPORT_DIR  "${BUILD_DIR}/reports"
set OUTPUT_DIR  "${BUILD_DIR}/outputs"

# ===========================================================================
# Step 0: Project configuration + environment check
# ===========================================================================
source ${SETUP_DIR}/setup.tcl
source ${SCRIPTS_DIR}/check-env.tcl

file mkdir ${BUILD_DIR} ${REPORT_DIR} ${OUTPUT_DIR}

# ===========================================================================
# Step 1: Load generic scripts (defines procs only, no side effects yet)
# ===========================================================================
source ${SCRIPTS_DIR}/mmmc.tcl
source ${SCRIPTS_DIR}/physical.tcl

puts "=================================================================="
puts "  SYN_ROOT   : $SYN_ROOT"
puts "  BUILD_DIR  : $BUILD_DIR"
puts "  TOP_MODULE : $TOP_MODULE"
puts "  INCR_MODE  : $INCR_MODE  CHECKPOINT: $INCR_CHECKPOINT"
puts "=================================================================="

# ===========================================================================
# Step 2: Clean slate
# ===========================================================================
remove_design -all

# ===========================================================================
# Step 3: Global timing-library setup (must precede elaborate / read_ddc)
# ===========================================================================
define_design_lib WORK -path ${BUILD_DIR}/WORK

mmmc_setup_global_libs $SRAM_MACROS

# ===========================================================================
# Step 4: Physical library setup
# ===========================================================================
physical_open_mw_lib

# ===========================================================================
# Step 5: Read / restore design
#   full flow            → source build/input.tcl (generated by gen_filelist.py)
#   incremental (any)    → read_ddc of the named checkpoint
# ===========================================================================

# Helper: resolve the DDC path for a given checkpoint name
proc checkpoint_ddc {phase} {
    global OUTPUT_DIR TOP_MODULE
    return ${OUTPUT_DIR}/${TOP_MODULE}_${phase}.ddc
}

# Helper: write a checkpoint DDC (no-op when ENABLE_CHECKPOINTS=0)
proc save_checkpoint {phase} {
    global ENABLE_CHECKPOINTS OUTPUT_DIR TOP_MODULE
    if {!$ENABLE_CHECKPOINTS} { return }
    set path [checkpoint_ddc $phase]
    puts "== \[checkpoint\] saving $phase -> $path"
    write -f ddc -hierarchy -output $path
}

if {$INCR_MODE} {
    set _ddc [checkpoint_ddc $INCR_CHECKPOINT]
    if {![file exists $_ddc]} {
        error "Checkpoint DDC not found: $_ddc\nRun full flow first (make syn)."
    }
    puts "== \[incr\] reading checkpoint: $_ddc"
    read_ddc $_ddc
    set ELAB_NAME [get_object_name [current_design]]
    puts "== \[incr\] restored design: $ELAB_NAME"
    link
} else {
    # Full flow: analyze RTL from the pre-generated build/input.tcl
    set _input_tcl ${BUILD_DIR}/input.tcl
    if {![file exists $_input_tcl]} {
        error "build/input.tcl not found. Run 'make gen_filelist' first."
    }
    source $_input_tcl

    # Elaborate
    elaborate ${TOP_MODULE} -library WORK
    set ELAB_NAME [get_object_name [current_design]]
    puts "== elaborated design: $ELAB_NAME"
    link

    # Mark SRAM macros dont_touch
    foreach macro $SRAM_MACROS {
        set cells [get_cells -hier -filter "ref_name == $macro" -quiet]
        if {[sizeof_collection $cells] > 0} {
            set_dont_touch $cells
            puts "   dont_touch: [sizeof_collection $cells]x $macro"
        }
    }

    # Unmapped (GTECH) Verilog: useful for hierarchy review and ECO reference
    write -f verilog -hierarchy -output ${OUTPUT_DIR}/${ELAB_NAME}_unmapped.v
    report_resources          > ${REPORT_DIR}/resources_precompile.rpt
    check_design              > ${REPORT_DIR}/check_design.rpt

    save_checkpoint post_elab
}

# ===========================================================================
# Step 6: MCMM scenarios + constraints
#   Skipped when resuming from post_constraints or post_compile
#   (scenarios are already embedded in the DDC)
# ===========================================================================

set _skip_constraints [expr {
    $INCR_MODE && (
        $INCR_CHECKPOINT eq "post_constraints" ||
        $INCR_CHECKPOINT eq "post_compile" ||
        $INCR_CHECKPOINT eq "final"
    )
}]

if {!$_skip_constraints} {
    mmmc_create_scenarios ${SETUP_DIR}/constraints.tcl $SRAM_MACROS
    physical_set_tluplus $ACTIVE_SCENARIOS
    check_design > ${REPORT_DIR}/check_design.rpt
    save_checkpoint post_constraints
} else {
    puts "== \[incr\] skipping scenario/constraint setup (resuming from $INCR_CHECKPOINT)"
    mmmc_set_active_scenarios $ACTIVE_SCENARIOS
}

# ===========================================================================
# Step 7: Compile
#   Skipped when resuming from post_compile (reports only)
# ===========================================================================

set _skip_compile [expr {
    $INCR_MODE && (
        $INCR_CHECKPOINT eq "post_compile" ||
        $INCR_CHECKPOINT eq "final"
    )
}]

if {!$_skip_compile} {
    set_host_options -max_cores $COMPILE_MAX_CORES

    # Build compile_ultra command from COMPILE_OPTIONS list
    set _compile_cmd "compile_ultra"
    foreach opt $COMPILE_OPTIONS {
        append _compile_cmd " $opt"
    }
    # Append -incremental when resuming from post_constraints
    if {$INCR_MODE && $INCR_CHECKPOINT eq "post_constraints"} {
        append _compile_cmd " -incremental"
    }

    puts "== \[compile\] $_compile_cmd"
    eval $_compile_cmd

    save_checkpoint post_compile
} else {
    puts "== \[incr\] skipping compile (resuming from $INCR_CHECKPOINT)"
}

# ===========================================================================
# Step 8: Post-compile outputs
# ===========================================================================
change_names -rules verilog -hier

write -f verilog -hierarchy -output ${OUTPUT_DIR}/${ELAB_NAME}_netlist.v

write_floorplan -all ${OUTPUT_DIR}/${ELAB_NAME}.fp
write_def -output ${OUTPUT_DIR}/${ELAB_NAME}.def
write_environment -format dctcl -output ${OUTPUT_DIR}/${ELAB_NAME}.environment.tcl

# Do not write topographical net RC as per-net set_load/set_resistance in SDC.
set_app_var write_sdc_output_lumped_net_capacitance false
set_app_var write_sdc_output_net_resistance false

write_parasitics -output ${OUTPUT_DIR}/${ELAB_NAME}.spef
write_sdf                    ${OUTPUT_DIR}/${ELAB_NAME}.sdf
write_sdc -nosplit           ${OUTPUT_DIR}/${ELAB_NAME}.sdc
saif_map -type ptpx -write_map ${OUTPUT_DIR}/${ELAB_NAME}.mapped.SAIF.namemap

# ===========================================================================
# Step 9: Reports
# ===========================================================================

# Summary reports
report_area   -hier -nosplit                                    > ${REPORT_DIR}/area.rpt
report_qor                                                      > ${REPORT_DIR}/qor.rpt
report_resources  -hierarchy                                    > ${REPORT_DIR}/resources_postcompile.rpt
report_clock_gating -nosplit                                    > ${REPORT_DIR}/clock_gating.rpt
report_congestion                                               > ${REPORT_DIR}/congestion.rpt

# Per-scenario reports
set _scen_dir ${REPORT_DIR}/scenarios
file mkdir ${_scen_dir}

foreach _s $ACTIVE_SCENARIOS {
    puts "   reporting scenario: $_s"
    mmmc_current_scenario $_s
    set _sd ${_scen_dir}/${_s}
    file mkdir ${_sd}

    report_clocks                                                     > ${_sd}/clocks.rpt
    report_power -nosplit -hierarchy -levels 3 -verbose               > ${_sd}/power.rpt
    report_power -nosplit -leakage_power_vt_breakdown                 > ${_sd}/power_leakage_vt.rpt
    report_power -nosplit -cell_power -sort_by leakage -verbose       > ${_sd}/power_cells_by_leakage.rpt
    report_threshold_voltage_group -nosplit                           > ${_sd}/threshold_voltage_group.rpt
    report_constraint -all_violators -nosplit                         > ${_sd}/violations.rpt
    report_timing -delay max -nosplit -max_paths ${MAX_PATHS}         > ${_sd}/timing_max.rpt
    report_timing -delay min -nosplit -max_paths ${MAX_PATHS}         > ${_sd}/timing_min.rpt
    report_timing -transition_time -nosplit -max_paths ${MAX_PATHS}   > ${_sd}/timing_transition.rpt
}

save_checkpoint final

puts "=================================================================="
puts "  Synthesis complete."
puts "  Outputs : $OUTPUT_DIR"
puts "  Reports : $REPORT_DIR"
puts "=================================================================="

exit
