# user spec file, compiler sram_sp_hde_shvt_mvt, version r6p0

EOL_guardband = 0
PG_PINS_domain = VDDPE
activity_factor = 50
atf = off
back_biasing = off
bit_blast = off
bits = 64
bmux = off
bus_notation = on
check_instname = on
compiler_type = sp
corners = 
cust_comment = 
diodes = on
drive = 6
dual_rail = off
ema = on
fci_type = not_fci
flexible_banking = 4
frequency = 500
instname = sram1024x64
irem_gds2_by_phyvtools = 0
left_bus_delim = [
libertyviewstyle = nldm
libname = sram_sp_hde
lren_bankmask = off
mux = 4
mvt = BASE
name_case = upper
pipeline = off
power_gating = off
power_type = otc
prefix = 
pwr_gnd_rename = vddpe:VDDPE,vddce:VDDCE,vsse:VSSE
ra = on
rcols = 2
redundancy = off
retention = on
right_bus_delim = ]
rows_p_bl = 256
rrows = 0
scan = off
ser = none
single_domain_only = on
site_def = off
triple_well = off
vmin_assist = on
wa = on
words = 1024
wp_size = 1
write_mask = on
write_thru = off
