#!/usr/bin/env python3
"""Convert a .f filelist (with -f includes, ${ROOT}, +incdir+, +define+)
into a tool-specific TCL read script.

Supported output formats (--format):
  vivado  — read_verilog / set_property include_dirs / set_property verilog_define
  genus   — set_db init_hdl_search_path / read_hdl -language sv|v2001
  dc      — analyze -format sverilog/verilog -vcs ...  (DC NXT)

Usage:
    python3 gen_filelist.py <filelist.f> <root_dir> --format vivado [-o build/sources.tcl]
    python3 gen_filelist.py <filelist.f> <root_dir> --format genus  [-o build/sources.tcl]
    python3 gen_filelist.py <filelist.f> <root_dir> --format dc     [-o build/input.tcl]
"""

import argparse
import os
import re
import sys


def resolve_vars(line, variables):
    """Replace ${VAR} with values from variables dict."""
    def replacer(m):
        return variables.get(m.group(1), m.group(0))
    return re.sub(r'\$\{(\w+)\}', replacer, line)


def parse_filelist(flist_path, variables, files, incdirs, defines, seen=None, is_F_mode=True):
    """Recursively parse a .f filelist.
    
    is_F_mode: Controls whether relative paths inside this filelist are relative 
               to the file itself (True, default for -F behavior) or relative to 
               the tool's running execution directory (False, for -f behavior).
    """
    if seen is None:
        seen = set()

    flist_path = os.path.normpath(flist_path)
    if flist_path in seen:
        return
    seen.add(flist_path)

    # 该 filelist 所在的目录
    base_dir = os.path.dirname(flist_path)

    with open(flist_path, 'r') as f:
        for raw_line in f:
            line = re.sub(r'//.*$', '', raw_line).strip()
            if not line:
                continue

            line = resolve_vars(line, variables)

            # 处理 -f 或 -F 嵌套文件列表
            if line.startswith('-f ') or line.startswith('-F '):
                is_sub_F = line.startswith('-F ')
                sub_file = line[3:].strip()
                
                # 无论如何，寻找嵌套 filelist 本身时，如果它是相对路径，
                # 在现代 EDA 工具中通常也是相对于当前 filelist 寻找的
                if not os.path.isabs(sub_file):
                    sub_path = os.path.join(base_dir, sub_file)
                else:
                    sub_path = sub_file
                
                # 递归调用，并将当前是 -f 还是 -F 的模式传递下去
                parse_filelist(sub_path, variables, files, incdirs, defines, seen, is_F_mode=is_sub_F)
                continue

            # --- 下面开始处理路径，根据 is_F_mode 决定以谁为基准 ---
            # 如果是 F 模式，以当前 .f 所在的 base_dir 为基准进行拼接；
            # 如果是 f 模式（且不是绝对路径），则保持原样（即相对于执行脚本的当前工作目录 '.'）
            
            # +incdir+
            if line.startswith('+incdir+'):
                path = line[8:].strip()
                if not os.path.isabs(path):
                    path = os.path.join(base_dir, path) if is_F_mode else path
                incdirs.add(os.path.normpath(path))
                continue

            # -I (alternative incdir)
            if line.startswith('-I'):
                path = line[2:].strip()
                if not os.path.isabs(path):
                    path = os.path.join(base_dir, path) if is_F_mode else path
                incdirs.add(os.path.normpath(path))
                continue

            # +define+ (与路径无关，直接处理)
            if line.startswith('+define+'):
                defines.add(line[8:].strip())
                continue

            # 普通 Source file 路径处理
            if not os.path.isabs(line):
                line = os.path.join(base_dir, line) if is_F_mode else line
            files.append(os.path.normpath(line))


def write_vivado(out, unique_files, incdirs, defines, src_filelist):
    out.write('# Auto-generated by gen_vivado_filelist.py  --format vivado\n')
    out.write(f'# Source: {src_filelist}\n\n')

    for f in unique_files:
        if f.endswith('.v'):
            out.write(f'read_verilog {{{f}}}\n')
        else:
            out.write(f'read_verilog -sv {{{f}}}\n')

    if incdirs:
        out.write('\n# Include directories\n')
        out.write('set_property include_dirs [list \\\n')
        for d in sorted(incdirs):
            out.write(f'  {{{d}}} \\\n')
        out.write('] [get_filesets sources_1]\n')

    if defines:
        out.write('\n# Verilog defines from filelists\n')
        defs_str = ' '.join(sorted(defines))
        out.write(f'set_property verilog_define {{{defs_str}}} [get_filesets sources_1]\n')

    out.write(f'\n# Total: {len(unique_files)} files, {len(incdirs)} include dirs\n')


def write_dc(out, unique_files, incdirs, defines, src_filelist):
    """Output a DC NXT analyze script (analyze -format sverilog/verilog -vcs ...)."""
    # Always inject SYNTHESIS define
    defines = set(defines) | {'SYNTHESIS'}

    sv_files = [f for f in unique_files if not f.endswith('.v')]
    v_files  = [f for f in unique_files if f.endswith('.v')]

    sorted_incdirs = sorted(incdirs)
    sorted_defines = sorted(defines)
    opts = ' '.join(
        [f'+define+{d}' for d in sorted_defines] +
        [f'+incdir+{d}' for d in sorted_incdirs]
    )
    opts = '{' + opts + '}'

    out.write('# Auto-generated by gen_filelist.py  --format dc  -- DO NOT EDIT\n')
    out.write(f'# Source  : {src_filelist}\n')
    out.write(f'# SV files: {len(sv_files)}   V files: {len(v_files)}\n')
    out.write(f'# Incdirs : {len(sorted_incdirs)}   Defines: {" ".join(sorted_defines)}\n\n')

    def emit_analyze(fmt, files):
        if not files:
            return
        out.write(f'analyze -format {fmt} -vcs \\\n')
        out.write(f'    {opts} \\\n')
        out.write('    [list \\\n')
        for f in files[:-1]:
            out.write(f'        {f} \\\n')
        out.write(f'        {files[-1]}\n')
        out.write('    ]\n\n')

    emit_analyze('sverilog', sv_files)
    emit_analyze('verilog',  v_files)


def write_genus(out, unique_files, incdirs, defines, src_filelist):
    # Always inject SYNTHESIS define
    defines = set(defines) | {'SYNTHESIS'}

    sv_files = [f for f in unique_files if not f.endswith('.v')]
    v_files  = [f for f in unique_files if f.endswith('.v')]

    sorted_incdirs = sorted(incdirs)
    sorted_defines = sorted(defines)
    opts = [f'+define+{d}' for d in sorted_defines] + \
           [f'+incdir+{d}' for d in sorted_incdirs]

    out.write('# Auto-generated by gen_vivado_filelist.py  --format genus  -- DO NOT EDIT\n')
    out.write(f'# Source  : {src_filelist}\n')
    out.write(f'# SV files: {len(sv_files)}   V files: {len(v_files)}\n')
    out.write(f'# Incdirs : {len(sorted_incdirs)}   Defines: {" ".join(sorted_defines)}\n\n')

    if sorted_incdirs:
        out.write('set_db init_hdl_search_path [list \\\n')
        for d in sorted_incdirs:
            out.write(f'  {{{d}}} \\\n')
        out.write(']\n\n')

    if sv_files:
        out.write('read_hdl -language sv \\\n')
        for opt in opts:
            out.write(f'  {opt} \\\n')
        for f in sv_files[:-1]:
            out.write(f'  {f} \\\n')
        out.write(f'  {sv_files[-1]}\n\n')

    if v_files:
        out.write('read_hdl -language v2001 \\\n')
        for opt in opts:
            out.write(f'  {opt} \\\n')
        for f in v_files[:-1]:
            out.write(f'  {f} \\\n')
        out.write(f'  {v_files[-1]}\n\n')


def main():
    parser = argparse.ArgumentParser(
        description='Convert a .f filelist to a tool-specific TCL read script')
    parser.add_argument('filelist', help='Input .f filelist')
    parser.add_argument('root',     help='Value for ${ROOT} variable')
    parser.add_argument('--format', choices=['vivado', 'genus', 'dc'], default='vivado',
                        help='Output format: vivado (default), genus, or dc')
    parser.add_argument('-o', '--output', default=None,
                        help='Output TCL file (default: sources.tcl / build/inputs.tcl / build/input.tcl)')
    parser.add_argument('--check', action='store_true',
                        help='Also print the resolved source-file list to stdout, one file per line')
    parser.add_argument('--var', action='append', default=[], metavar='KEY=VALUE',
                        help='Extra filelist variables (e.g. SOC_CONFIG=minimum_my_mxu)')
    args = parser.parse_args()

    if args.output is None:
        defaults = {'vivado': 'sources.tcl', 'genus': 'build/inputs.tcl', 'dc': 'build/input.tcl'}
        args.output = defaults[args.format]

    root = os.path.normpath(os.path.abspath(args.root))
    variables = {'ROOT': root}
    for item in args.var:
        if '=' not in item:
            print(f'[gen_filelist] ERROR: --var expects KEY=VALUE, got: {item!r}',
                  file=sys.stderr)
            sys.exit(1)
        key, value = item.split('=', 1)
        variables[key] = value

    files = []
    incdirs = set()
    defines = set()
    parse_filelist(args.filelist, variables, files, incdirs, defines)

    # Deduplicate files while preserving order
    seen = set()
    unique_files = []
    for f in files:
        if f not in seen:
            seen.add(f)
            unique_files.append(f)

    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or '.', exist_ok=True)

    writers = {'vivado': write_vivado, 'genus': write_genus, 'dc': write_dc}
    with open(args.output, 'w') as out:
        writers[args.format](out, unique_files, incdirs, defines, args.filelist)

    if args.check:
        for f in unique_files:
            print(f)

    sv_count = sum(1 for f in unique_files if not f.endswith('.v'))
    v_count  = len(unique_files) - sv_count
    status_out = sys.stderr if args.check else sys.stdout
    print(f'[gen_filelist] [{args.format}] -> {args.output}  '
          f'({sv_count} SV + {v_count} V, {len(incdirs)} incdirs, {len(defines)} defines)',
          file=status_out)


if __name__ == '__main__':
    main()
