# user spec file, compiler rf_sp_hde_shvt_mvt, version r3p1

PG_PINS_domain = VDDCE
activity_factor = 50
atf = off
back_biasing = off
bit_blast = off
bits = 46
bmux = off
bus_notation = on
check_instname = on
compiler_type = ULL
corners = 
cust_comment = This\ is\ a\ memory\ instance
diodes = on
drive = 6
dual_rail = off
ema = on
frequency = 500
instname = sram128x46
irem_gds2_by_phyvtools = 0
left_bus_delim = [
libertyviewstyle = nldm
libname = rf_sp_hde
mux = 2
mvt = BASE
name_case = lower
pipeline = off
power_gating = off
power_type = otc
pwr_gnd_rename = vddpe:VDDPE,vddce:VDDCE,vsse:VSSE
ra = on
rcols = 2
redundancy = off
retention = on
right_bus_delim = ]
rrows = 0
ser = none
single_domain_only = on
site_def = off
top_layer = m5-m10
triple_well = off
vmin_assist = on
wa = on
words = 128
wp_size = 1
write_mask = off
write_thru = off
